#!/bin/bash
cd /Users/redesigndavid/projects/ 
for i in cBoid2x ; do
echo "tagging $i"
pushd $i
/usr/local/bin/ctags -f ~/.vimtags/$i -R \
--exclude='.git' \
--langmap=objc:.m.h \
--totals=yes \
--tag-relative=yes \
--regex-objc='/^[[:space:]]*[-+][[:space:]]*\([a-zA-Z_]+[[:space:]]*\*?\)[[:space:]]*([a-zA-Z_0-9]+):*[[:space:]]*/\1/m,method/' \
--regex-objc='/^[[:space:]]*[-+][[:space:]]*\([a-zA-Z_]+[[:space:]]*\*?\)[[:space:]]*([a-zA-Z_0-9]+):[[:space:]]*\(/\1/m,method/' \
--regex-objc='/^[[:space:]]*[-+][[:space:]]*\([a-zA-Z_]+[[:space:]]*\*?\)[[:space:]]*([a-zA-Z_0-9]+)[[:space:]]*\{/\1/m,method/' \
--regex-objc='/^[[:space:]]*[-+][[:space:]]*\([a-zA-Z_]+[[:space:]]*\*?\)[[:space:]]*([a-zA-Z_0-9]+)[[:space:]]*\;/\1/m,method/' \
--regex-objc='/^[[:space:]]*\@property[[:space:]]+.*[[:space:]]+\*?(.*);$/\1/p,property/' \
--regex-objc='/^[[:space:]]*\@implementation[[:space:]]+(.*)$/\1/c,class/' \
--regex-objc='/^[[:space:]]*\@interface[[:space:]]+(.*)[[:space:]]+:.*{/\1/i,interface/'
popd
 
done;
